### ISSUE TITLE
Implement caching for transport

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio-keeper#113]
Transport should keep connection open for a certain time when sending and reuse them if sending to the same node again. One way of implementing this is to have a Ref[Map[Address, Channel]] that is created on construction of the transport and periodically garbage collected.

**Comment by pshemass** [comment]
This sound like connection pool. IMHO this should not be part of transport. Transport should be an trait with method ```send```

```
trait Transport {
  def send(data: Chunk[Byte]): ZIO[R, TransportError, Unit]
  // We could add method to check health 
}

class tcp(socket: ZManaged[AsynchronousSocketChannel]) {
  def send(data: Chunk[Byte]): ZIO[R, TransportError, Unit] = ???
}
object tcp {
 def apply(to: SocketAddress, 
    maxConnections: Int,
    connectionTimeout: Duration,
    sendTimeout: Duration): ZIO[Any, TransportError, Transport] = ???
```

or maybe transport is just factory that return connection which would have the same interface as Transport above. What do you think @mschuwalow ?

**Comment by mijicd** [comment]
Closing it as it doesn't belong at this level.
