### ISSUE TITLE
Implement InMemoryTransport

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio-keeper#114]
Implementation of Transport that works completely in memory. It additionally support a percentMessageDrop parameter that causes a certain percentage of all messages to be dropped.
Furthermore it should have an api that allows to simulate network partitions between hosts.

**Comment by pshemass** [comment]
I understand that this is mostly for testing things locally, right?

**Comment by vasilmkd** [comment]
I'd like to work on this. :pray:

**Comment by vasilmkd** [comment]
I'm a bit confused. How does an in memory implementation tie in with the `SocketAddress` centric transport service?

**Comment by vasilmkd** [comment]
I see that this has been tackled as part of #180.

**Comment by mschuwalow** [comment]
Depending on what we end up doing with tcp/udp there might be more work required so let's leave this open for now
