### ISSUE TITLE
Clean the code

### ISSUE THREAD

**Issue by mijicd** [zio/zio-keeper#115]
The current implementation can be polished in terms of cleanliness. The things that I'd propose doing in the first run are:

- [ ] ensure return type is specified for all functions
- [x] order functions alphabetically
- [x] extract versions of ZIO to variables in build.sbt

**Comment by naseem91** [comment]
I want to take this

**Comment by klangner** [comment]
Is anyone working on adding return types to the functions?
If not I can do it.

**Comment by mijicd** [comment]
@klangner yes, there's already an [in-progress PR](#151). Feel free to jump in there in case @naseem91 needs any help!

**Comment by ZheniaTrochun** [comment]
Since [mentioned earlier PR](https://github.com/zio/zio-keeper/pull/151) has been closed, I would like to work on return types.

**Comment by mijicd** [comment]
@ZheniaTrochun all yours, feel free to fix any other discrepancies you see.

**Comment by mijicd** [comment]
Closed in #252
