### ISSUE TITLE
Add correlationId to message

### ISSUE THREAD

**Issue by pshemass** [zio/zio-keeper#116]
All messages in the cluster should have identifier. When message are part of the same "transaction" they should have the same prefix in order to group them together.

**Comment by klangner** [comment]
Do I understand it correctly that I should add `id` to the class `Message` to implement it?
Of course this will require changes in serialization and probably other part.
This id should have String type?

**Comment by mijicd** [comment]
@klangner exactly. It can be UUID or any alternative identifier you propose.

**Comment by klangner** [comment]
I will work on it then.

**Comment by mijicd** [comment]
Closed in #160
