### ISSUE TITLE
OOM when running example

### ISSUE THREAD

**Issue by klangner** [zio/zio-keeper#158]
If I start `Node1` only everything is ok.
But if I also start `Node2`, then after some time (5-10 minutes) `Node1` will crash with:
```
java.lang.OutOfMemoryError: Java heap space
```

**Comment by pshemass** [comment]
@klangner start `Node1` then `Node2` by running `sbt examples/run` and I couldn't have reproduce this. 

not even sign of OOM 
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/3524653/73716370-cfbd5100-46e4-11ea-84bb-02820722da29.png">

Could you tell me more about your setup?

**Comment by klangner** [comment]
I'm on Mac. I run them in separate terminal windows. You should find this exception there

**Comment by pshemass** [comment]
I don't see it. I ran this for 20min and nothing as you see on the diagrams. I'm close that because I cannot reproduce.
