### ISSUE TITLE
Use STM.foreach_ wherever possible

### ISSUE THREAD

**Issue by mschuwalow** [zio/zio-keeper#163]
Can only be resolved once we have upgraded ZIO version

**Comment by chlin501** [comment]
I am interested and would like to take this issue. 

By the way, after cloning the repo (the latest revision is 
eadb32f453fcb97f742023595148c4076e0e4aee), I notice that in BuildHelper.scala zioVersion is "1.0.0-RC21-2", that contains STM. So I suppose this ticket doesn't need to upgrade zio to a newer version, right?

**Comment by mijicd** [comment]
@chlin501 No, we updated the zio version roughly a week ago. Now it's up to you to nuke `foreach` wherever applicable :).

**Comment by chlin501** [comment]
I created the PR [1]. It looks like only 2 files referenced to (Z)STM.foreach(). Please let me know if I miss any code that also references to (Z)STM.foreach(), or any issues in terms of this. I will update it again. Thanks!

[1]. https://github.com/zio/zio-keeper/pull/270

**Comment by mijicd** [comment]
Closed in #270
