### ISSUE TITLE
Upgrade ZIO to 1.0.0-RC18

### ISSUE THREAD

**Issue by mijicd** [zio/zio-keeper#172]
~Due to the large amount of new features, and delay of RC18 (or 1.0.0 :)), we will depend on snapshot version in order to align our APIs with the latest changes and prepare for an official release.~

**Comment by mijicd** [comment]
Re-purposing this one to update ZIO to `1.0.0-RC18`.

**Comment by vasilmkd** [comment]
Picking this up.

**Comment by mschuwalow** [comment]
@vasilmkd note that this is currently using zio-macros quite heavily. 

As we / zio-macros will not publish the parts relevant for this library starting with zio 1.0.0-RC18, the migration to ZLayer has to be be done as part of this.

**Comment by vasilmkd** [comment]
@mschuwalow I'm aware, thanks.

**Comment by vasilmkd** [comment]
Waiting on the `zio-logging` release with `ZLayer`.

**Comment by pshemass** [comment]
@vasilmkd working on that now

**Comment by pshemass** [comment]
@vasilmkd `zio-logging` 0.2.3 with RC18 released. let me know if you need any help

**Comment by vasilmkd** [comment]
Thanks. It's going well.

**Comment by vasilmkd** [comment]
Done with the `keeper` module. Now onwards with the `membership` module.

**Comment by vasilmkd** [comment]
This can probably be closed. Sorry I didn't link this from the PR. #188
