### ISSUE TITLE
Data serialization

### ISSUE THREAD

**Issue by mijicd** [zio/zio-keeper#19]
Nodes will exchange a lot of operational and metadata over network. We should try to minimize the traffic and reduce the serialization / deserialization footprint as much as possible. The focus of this issue is to design an (close to) optimal message representation, and decide on the serialization format.

In my opinion, some of the strong candidates are Protobuf, Avro, and Thrift, but there are many more available. We should keep an eye on [scalaz-schema](https://github.com/scalaz/scalaz-schema/) as it will eventually provide all necessary "tools".

**Comment by GrafBlutwurst** [comment]
you rang? We'd be happy to work with you all on that. We don't have the implementations for Protobuf, Avro, or Thrift as of now but that is really only a matter of time. Feel free to just @ me about that though

**Comment by mijicd** [comment]
I know there is an open issue for Avro support. Since we spoke about working together on that one (a long time ago), this might be the opportunity to do so :).

**Comment by pshemass** [comment]
@mijicd right now we are serialize our internal protocol messages manually using ByteBuffer from zio-nio. Since we want to keep dependency as small as possible do you thing we should still look into scalaz-schema or other serialization framework?

**Comment by pshemass** [comment]
we decided to use http://www.lihaoyi.com/upickle/#µPickle0.8.0

**Comment by pshemass** [comment]
done by #121
