### ISSUE TITLE
Adding logging 

### ISSUE THREAD

**Issue by pshemass** [zio/zio-keeper#45]
currently we log to console using `zio.console.Console` which obviously is not production solution. We may use some of existing libs for that.  

Potential candidates are:
1. https://github.com/NeQuissimus/zio-slf4j - it's depending on scalaz and since we are trying to minimize dependency we probable don't want to use it.
2. https://izumi.7mind.io/latest/release/doc/logstage/ - it seems to work and it's documented

other option would be to create zio-logger project with very simple interface that would be easy to plug to slf4j or whatever.

@jdegoes @mijicd Thoughts?

**Comment by jdegoes** [comment]
@pshemass Agreed! Let's do a `ZIO Logger` project with minimal environmental interface. Then it can have lots of implementations in other projects (and maybe 1 or 2 in core).

**Comment by mijicd** [comment]
Closing it as ZIO logger is in place, and integrated with ZIO keeper!
