### ISSUE TITLE
Define CRDTs

### ISSUE THREAD

**Issue by mijicd** [zio/zio-keeper#6]
The decision has been made to use conflict-free replicated data types (CRDTs) for providing consistency guarantees. The purpose of this issue is to make an agreement upon the data structures and the strategy (state vs operational) that we will provide in the first release.

### Prerequisites

In case you are not familiar with the concept, the following videos provide a (relatively) gentle introduction:

- [CRDTs illustrated](https://www.youtube.com/watch?v=9xFfOhasiOE)
- [Strong Eventual Consistency and Conflict-free Replicated Data Types](https://www.youtube.com/watch?v=ebWVLVhiaiY)
- [CRDTs in Practice](https://www.youtube.com/watch?v=xxjHC3yLDqw)

For an in-depth understanding of CRDTs, please make sure to check out [this paper](https://hal.inria.fr/hal-00932836/file/CRDTs_SSS-2011.pdf).

**Comment by mijicd** [comment]
@pshemass raised the hand for this one. Our agreement is to provide an initial draft as part of this issue and complete the implementation in follow-ups.

**Comment by pshemass** [comment]
As I mentioned on Friday meeting the plan is to implement as first OR-Set with Vector Clock as operation identifier generator. 

This work will require 
* algebras for OR-Set and  operations(add and remove) that can be send over a wired 
* implementation of vector clock 
* implementation of OR-Set logic.
* integration with current API  

I will work on the details with @rabbitonweb

**Comment by pshemass** [comment]
WIP: https://github.com/pshemass/scalaz-distributed/tree/feature/crdt-or-set

**Comment by mijicd** [comment]
Might be an interesting read: [Efficient Synchronization of State-based CRDTs](https://arxiv.org/abs/1803.02750).

**Comment by pshemass** [comment]
@mijicd could we should add all of the materials here from Peter and continue discussion here.

**Comment by mijicd** [comment]
This ticket went out of the project scope. I will reopen in case anything changes.
