### ISSUE TITLE
Implement Gossip

### ISSUE THREAD

**Issue by mijicd** [zio/zio-keeper#7]
Before obtaining an access to metadata API, one has to join the cluster and obtain the public "access protocol" (see #2). [Gossip protocol](https://en.wikipedia.org/wiki/Gossip_protocol) should be used to exchange the data necessary for successful bootstrap. 

**Note:** Due to the size of this issue, the preferable approach is to split the implementation in multiple pull requests.

**Comment by jdegoes** [comment]
See [here](https://pdfs.semanticscholar.org/7dee/bf532a927293c6c064765a62253770061035.pdf) for an example that takes into consideration geometry (AKA routing times between nodes).

**Comment by jdegoes** [comment]
Scalaz NIO is in great shape as a basis for this.

**Comment by sasiharan** [comment]
@mijicd I would like to work on this issue.

**Comment by mijicd** [comment]
@sasiharan It's yours. Let me know if you need any help.

**Comment by pshemass** [comment]
lessons learnt from HashiCorp Consule gossip implementation https://arxiv.org/pdf/1707.00788.pdf

**Comment by rabbitonweb** [comment]
"The Promise, and Limitations, of Gossip Protocols" by Ken Birman http://www.cs.cornell.edu/Projects/Quicksilver/public_pdfs/2007PromiseAndLimitations.pdf

**Comment by mijicd** [comment]
More interesting materials about Gossip:
- https://www.youtube.com/watch?v=u-a7rVJ6jZY (related to the Hashicorp paper above)
- https://www.youtube.com/watch?v=QQ2n1UX3Qwg (protocol overview with a lot of references)
- ["Epidemic Algorithms for Replicated Database Maintenance"](http://bitsavers.informatik.uni-stuttgart.de/pdf/xerox/parc/techReports/CSL-89-1_Epidemic_Algorithms_for_Replicated_Database_Maintenance.pdf) by A. Demers & co.

**Comment by pshemass** [comment]
@mijicd Could you add here specification of how we want to implement that?

**Comment by mijicd** [comment]
For sure, as discussed over chat, let's have a session and design the layer properly.

**Comment by mijicd** [comment]
Closed in #66. To be followed-up and polished in subsequent issues.
