### ISSUE TITLE
Upgrade zio-nio version

### ISSUE THREAD

**Issue by mijicd** [zio/zio-keeper#92]
The current implementation of `zio-keeper` uses `zio-nio:0.1.2`. To be able to upgrade the version, and utilise the latest features shipped in `zio-nio`, `zio-keeper` internals needs to be updated to work with `ZManaged`.

**Comment by mijicd** [comment]
Putting on hold until we have all of the PRs merged in `zio-nio` and `zio`.

**Comment by pshemass** [comment]
the PR could be merge thought so we can start working on remaining issues

**Comment by mijicd** [comment]
@pshemass we come up to the better encoding, we'll provide issues!
